# Generated by Django 3.0.3 on 2020-04-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200414_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
