# Generated by Django 3.0.3 on 2020-04-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_blogarticle_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
